---
title: "Boston"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```


```{r }
library(MASS)
data(Boston)
```


```{r}
ls()
rm()
rnorm()
set.seed()
var()
sd()
contour()
image()
persp()
fix()
coef()
confint()
predict()
abline()
lm()
glm()
lda()
qda()
knn()
scale()
table()
cbind()
rbind()
par()
residuals()
rstudent()
vif()
anova()
contrasts()
c()
%in%
%>%
ggplot()
geom_point()
arrange()
filter()
summarise()
```


```{r}
#LR
fix(Boston)
names(Boston)
lm.fit=lm(medv∼lstat , data=Boston)
attach(Boston)
lm.fit=lm(medv∼lstat)
lm.fit
summary (lm.fit)
names(lm.fit)
coef(lm.fit)
confint(lm.fit)
predict( lm.fit , data.frame( lstat=c( 5,10,15 ) ) , interval ="confidence")
predict( lm.fit , data.frame( lstat=c( 5,10,15 ) ) , interval ="prediction")
plot(lstat ,medv)
```

```{r}
#abline(lm.fit)
#abline ( lm.fit , lwd =3 )
#abline ( lm.fit , lwd=3 , col = "red" )
plot(lstat ,medv ,col="red")
plot(lstat ,medv ,pch =20)
plot(lstat ,medv ,pch ="+")
plot(1:20,1:20,pch =1:20)
```

```{r}
par(mfrow=c(2,2))
plot(lm.fit)
plot(predict (lm.fit), residuals (lm.fit))
plot(predict (lm.fit), rstudent (lm.fit))
plot(hatvalues (lm.fit))
which.max(hatvalues (lm.fit))
```


```{r}
#MR
lm.fit=lm(medv∼lstat+age ,data=Boston )
summary (lm.fit)

lm.fit=lm(medv∼.,data=Boston)
summary (lm.fit)

library (car)
vif(lm.fit)

lm.fit1=lm(medv∼.-age ,data=Boston )
summary (lm.fit1)
```

