---
title: "DSCI353-353m-453: LE1c-ISLR-Lin-MultRegr"
author: "Roger H. French, Peitian Wang"
subtitle: "2001-353-353m-453-LE1c-ISLR-Lin-MultRegr-NAME.Rmd"
date: "`r format(Sys.time(), '%d %B, %Y')`"
output:
  pdf_document:
    latex_engine: xelatex
    toc: true
    number_sections: true
    toc_depth: 6
  html_document:
    font-size: 10em
    self_contained: yes
    toc: yes
urlcolor: blue
---

Use ISLR Chapter 3 for this assignment

10 questions, 2 point total, so 0.2 points each.

# 3.1.R1  (1 point possible)

## Why is linear regression important to understand? Select all that apply:

  1. The linear model is often correct  
  2.  Linear regression is very extensible and can be used to capture nonlinear effects  
  3.  Simple methods can outperform more complex ones if the data are noisy  
  4. Understanding simpler methods sheds light on more complex ones

  ####Answer : (2) (3) (4)


# 3.1.R2  (1 point possible)

You may want to reread the paragraph on confidence intervals on page 66 of the textbook before trying this queston (the distinctions are subtle).

## Which of the following are true statements? Select all that apply:

  1. A 95% confidence interval is a random interval that contains the true parameter 95% of the time  
  2. The true parameter is a random value that has 95% chance of falling in the 95% confidence interval  
  3. I perform a linear regression and get a 95% confidence interval from 0.4 to 0.5. There is a 95% probability that the true parameter is between 0.4 and 0.5.  
  4. The true parameter (unknown to me) is 0.5. If I sample data and construct a 95% confidence interval, the interval will contain 0.5 95% of the time.

  ####Answer : (2) (3)

# 3.2.R1  (1 point possible)

We run a linear regression and the slope estimate is 0.5 with estimated standard error of 0.2. 

## What is the largest value of $b$ for which we would NOT reject the null hypothesis that $\beta_1=b$? 

  * (assume normal approximation to t distribution, and 
  * that we are using the 5% significance level for a two-sided test; 
  * need two significant digits of accuracy)

  ###Answer : 1.96*0.2==0.392

# 3.2.R2  (1 point possible)

## Which of the following indicates a fairly strong relationship between X and Y?

  1. $R^2=0.9$  
  2. The p-value for the null hypothesis $\beta_1=0$ is 0.0001  
  3. The t-statistic for the null hypothesis $\beta_1=0$ is 30

  ###Answer : (2)

# 3.3.R1  (1/1 point)

Suppose we are interested in learning about a relationship between X1 and Y, which we would ideally like to interpret as causal.

  ## True or False?  


The estimate $\hat{\beta}_1$ in a linear regression that controls for many variables (that is, a regression with many predictors in addition to $X_1$) is usually a more reliable measure of a causal relationship than $\hat{\beta}_1$ from a univariate regression on $X_1$.

  ###ANS: False

# 3.4.R1  (1/1 point)

According to the balance vs ethnicity model, 

## what is the predicted balance for an Asian in the data set? (within 0.01 accuracy)

  ###Answer : 
          531-18.69(X)(asian)-12.50(X)(caucasian) == 531-18.69 == 512.31


# 3.4.R2  (1/1 point)

## What is the predicted balance for an African American? (within .01 accuracy)

  ###Answer : 531-0 == 531

# 3.5.R1  (1/1 point)

According to the model for sales vs TV interacted with radio, 

## what is the effect of an additional $1 of radio advertising if TV=$50? (with 4 decimal accuracy)

  ###Answer : 0.0289+0.0011*(TV) == 0.0839

# 3.5.R2  (1/1 point)

## What if TV=$250? (with 4 decimal accuracy)

  ###Answer : 0.0289+0.0011*(TV) == 0.3039

# 3.R.R1  (1 point possible)

What is the difference between `lm(y ~ x*z)` and `(y ~ I(x*z))`, when x and z are both numeric variables?

  1. The first one includes an interaction term between x and z, whereas the second uses the product of x and z as a predictor in the model.  
  2.The second one includes an interaction term between x and z, whereas the first uses the product of x and z as a predictor in the model.  
  3. The first includes only an interaction term for x and z, while the second includes both interaction effects and main effects.  
  4. The second includes only an interaction term for x and z, while the first includes both interaction effects and main effects.

  ###Answer : (4)

# Cites

* Gareth James, Daniela Witten, Trevor Hastie, and Robert Tibshirani. An Introduction to Statistical Learning: With Applications in R. 1st ed. 2013, Corr. 5th printing 2015 edition. Springer Texts in Statistics. New York: Springer, 2013.

